#ifndef CONFIG_H_
#define CONFIG_H_

#cmakedefine CPPUTEST_HAVE_FORK
#cmakedefine CPPUTEST_HAVE_WAITPID
#cmakedefine CPPUTEST_HAVE_KILL
#cmakedefine CPPUTEST_HAVE_PTHREAD_MUTEX_LOCK

#cmakedefine CPPUTEST_HAVE_GETTIMEOFDAY

#cmakedefine CPPUTEST_STD_CPP_LIB_DISABLED

#endif
