---
name: Basic builds

"on":
  push:
  pull_request:

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - uses: DoozyX/clang-format-lint-action@v0.14
        with:
          clangFormatVersion: 14
          source: examples

  codeql:
    runs-on: ubuntu-20.04
    env:
      CC: gcc-10
      CXX: g++-10
    name: "CodeQL"
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: CodeQL Initialization
        uses: github/codeql-action/init@v2
        with:
          languages: cpp
          queries: +security-and-quality
      - name: Build
        run: |
          mkdir _build && cd _build
          cmake -DCMAKE_CXX_STANDARD=17 ..
          make -j2
      - name: CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  autotools:
    strategy:
      matrix:
        include:
          - name: Mac GNU
            os: macos-latest
            cc: gcc
            cxx: g++
            target: tdd
          - name: Mac Clang
            os: macos-latest
            cc: clang
            cxx: clang++
            target: tdd
          - name: Linux GNU
            os: ubuntu-latest
            cc: gcc
            cxx: g++
            target: tdd
          - name: Linux Clang
            os: ubuntu-latest
            cc: clang
            cxx: clang++
            target: tdd
          - name: No long long
            os: ubuntu-latest
            configure_flags: --disable-longlong
            target: tdd
          - name: Google Test 1.5
            os: ubuntu-latest
            target: check_gtest15
            apt_packages: python2
          - name: Google Test 1.6
            os: ubuntu-latest
            target: check_gtest16
            apt_packages: python2
          - name: Google Test 1.7
            os: ubuntu-latest
            target: check_gtest17
            apt_packages: python2
          - name: Google Test 1.8
            os: ubuntu-latest
            target: check_gtest18
            apt_packages: python2
    name: "autotools: ${{ matrix.name }}"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install packages (Linux)
        run: sudo apt install -y ${{ matrix.apt_packages }}
        if: ${{ matrix.apt_packages }}
      - name: Install packages (Mac)
        run: brew install automake
        if: ${{ startswith(matrix.os, 'macos') }}
      - name: Checkout
        uses: actions/checkout@main
      - if: ${{ matrix.cxx }}
        run: echo "CXX=${{ matrix.cxx }}" >> $GITHUB_ENV
      - if: ${{ matrix.cc }}
        run: echo "CC=${{ matrix.cc }}" >> $GITHUB_ENV
      - name: Configure
        run: |
          autoreconf -i .
          ./configure ${{ matrix.configure_flags }}
      - name: Build and test
        run: make ${{ matrix.target }}

  cmake:
    strategy:
      matrix:
        include:
          - name: MSVC defaults
            os: windows-latest
            cpp_version: 17
            preset: MSVC
            # install: true
          - name: MSVC 20
            os: windows-latest
            cpp_version: 20
            preset: MSVC
          - name: ClangCL
            os: windows-latest
            cpp_version: 17
            preset: ClangCL
          - name: Linux Clang 98
            os: ubuntu-latest
            cpp_version: 98
            preset: Clang
          - name: Linux Clang 11
            os: ubuntu-latest
            cpp_version: 11
            preset: Clang
          - name: Linux Clang 14
            os: ubuntu-latest
            cpp_version: 14
            preset: Clang
          - name: Linux Clang 17
            os: ubuntu-latest
            cpp_version: 17
            preset: Clang
          - name: Linux Clang 20
            os: ubuntu-latest
            cpp_version: 20
            preset: Clang
          - name: Linux GNU 98
            os: ubuntu-latest
            cpp_version: 98
            preset: GNU
          - name: No long long
            os: ubuntu-latest
            cpp_version: 98
            preset: no-long-long
          - name: Detailed
            os: ubuntu-latest
            cpp_version: 98
            preset: detailed
          - name: Linux GNU Install
            os: ubuntu-latest
            cpp_version: 11
            preset: GNU
            install: true
          - name: Linux GNU 14
            os: ubuntu-latest
            cpp_version: 14
            preset: GNU
          - name: Linux GNU 17
            os: ubuntu-latest
            cpp_version: 17
            preset: GNU
          - name: Linux GNU 20
            os: ubuntu-latest
            cpp_version: 20
            preset: GNU
          - name: MinGW
            os: ubuntu-latest
            cpp_version: 11
            preset: MinGW
            apt_packages: mingw-w64 wine64
          - name: No C++ Standard Library
            os: ubuntu-latest
            cpp_version: 98
            preset: no-std-cpp
          - name: Coverage
            os: ubuntu-latest
            cpp_version: 11
            preset: coverage
            apt_packages: lcov
          - name: GCC ARM embedded
            os: ubuntu-latest
            cpp_version: 11
            preset: arm-embedded
          - name: Mac install
            os: macos-latest
            cpp_version: 98
            preset: defaults
            install: true
          - name: Apple Clang 17
            os: macos-latest
            cpp_version: 17
            preset: Clang
          - name: Apple Clang 20
            os: macos-latest
            cpp_version: 20
            preset: Clang
          - name: Mac GNU 14
            os: macos-latest
            cpp_version: 14
            preset: GNU
          - name: OpenWatcom DOS
            os: ubuntu-latest
            cpp_version: 98
            preset: DOS
            apt_packages: dosbox
    name: "CMake: ${{ matrix.name }}"
    runs-on: ${{ matrix.os }}
    steps:
      ### SETUP

      - name: Install packages
        run: sudo apt install -y ${{ matrix.apt_packages }}
        if: ${{ matrix.apt_packages }}

      - uses: carlosperate/arm-none-eabi-gcc-action@v1
        if: ${{ matrix.name == 'GCC ARM embedded' }}
      - name: Install QEMU
        # The version in the ubuntu repositories (6.2) is broken.
        run: |
          wget -nv http://ftp.de.debian.org/debian/pool/main/q/qemu/qemu-user-static_7.1+dfsg-2_amd64.deb -O qemu.deb
          sudo dpkg --install qemu.deb
          rm -f qemu.deb
        if: ${{ matrix.name == 'GCC ARM embedded' }}

      - name: Install OpenWatcom
        uses: open-watcom/setup-watcom@v0
        with:
          version: "2.0"
        if: ${{ matrix.name == 'OpenWatcom DOS' }}

      ## BUILD AND TEST

      - name: Checkout
        uses: actions/checkout@main
      - name: Configure
        run: cmake --preset ${{ matrix.preset }} -D CMAKE_CXX_STANDARD=${{ matrix.cpp_version }}
      - name: Build
        run: cmake --build cpputest_build --verbose
      - name: Test
        run: ctest --test-dir cpputest_build

      # POST PROCESSING

      - name: Install
        run: sudo cmake --install cpputest_build/
        if: ${{ matrix.install }}
      - name: Use install
        run: |
          cmake -B build -S examples
          cmake --build build -j
          ctest --test-dir build
        if: ${{ matrix.install }}

      - name: Coverage
        run: |
          lcov --capture --directory . --no-external --output-file lcov.info
          lcov --remove lcov.info --output-file lcov.info '*/tests/*'
        if: ${{ matrix.name == 'Coverage' }}
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ matrix.name == 'Coverage' }}

  make_dos:
    runs-on: ubuntu-latest
    name: "Make: DOS"
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Install tools
        run: |
          sudo apt-get install -y dosbox
          git clone https://github.com/cpputest/watcom-compiler.git watcom
          echo "WATCOM=$GITHUB_WORKSPACE/watcom" >> $GITHUB_ENV
          echo "CC=wcl" >> $GITHUB_ENV
          echo "CXX=wcl" >> $GITHUB_ENV
          echo "$GITHUB_WORKSPACE/watcom/binl" >> $GITHUB_PATH
          echo "CPPUTEST_HOME=$GITHUB_WORKSPACE" >> $GITHUB_ENV
      - name: Build
        run: |
          $CC --version
          make -f $CPPUTEST_HOME/platforms/Dos/Makefile clean
          make -f $CPPUTEST_HOME/platforms/Dos/Makefile
      - name: Test
        env:
          TERM: linux
        run: $CPPUTEST_HOME/platforms/Dos/alltests.sh
