---
name: push

on:
  push:

jobs:
  defaults:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Configure
        run: cmake --preset defaults
      - name: Build
        run: cmake --build build/defaults -j
      - name: Test
        run: ctest --test-dir build/defaults
