---
name: push

on:
  push:

jobs:
  basic:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            preset: defaults
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Configure
        run: cmake --preset ${{ matrix.preset }}
      - name: Build
        run: cmake --build build/${{ matrix.preset }} -j
      - name: Test
        run: ctest --test-dir build/${{ matrix.preset }}
